name: build

on:
  push:
    branch:
      - "master"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Log in to the Container registry
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build Docker Image
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: false
      #     tags: buildroot
      # ghcr.io/ciiiii/buildroot-pulsar:latest
      # ghcr.io/ciiiii/buildroot-pulsar:${{ github.sha }}
      
      # make invisible-mirror.net fail fast
      # ref: https://github.com/actions/runner-images/issues/2577#issuecomment-845126269
      - name: Build the iso
        run: |
          docker run \
            --rm \
            --name build-v86 \
            -v $PWD/dist:/build \
            -v $PWD/buildroot-v86/:/buildroot-v86 \
            --add-host=invisible-mirror.net:1.1.1.1 \
            ghcr.io/ciiiii/buildroot-pulsar:latest

      - name: Check the iso
        run: ls -lh dist/v86-linux.iso

      - name: Archive the iso
        uses: actions/upload-artifact@v3
        with:
          name: buildroot-v86
          path: dist/v86-linux.iso

  # build-iso:
  #   runs-on: ubuntu-latest
  #   needs: docker-build
  #   container:
  #     image: ghcr.io/ciiiii/buildroot-pulsar:latest
  #     volumes:
  #     - ${GITHUB_WORKSPACE}/dist:/build
  #     - ${GITHUB_WORKSPACE}/buildroot-v86/:/buildroot-v86
  #   steps:
  #   - name: Check the iso
  #     run: ls -lh dist/v86-linux.iso

  #   - name: Archive the iso
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: buildroot-v86
  #       path: dist/v86-linux.iso
